footprint: [[0.362, -0.308], [0.362, 0.308], [-0.362,0.308], [-0.362, -0.308]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.3

obstacle_laser_layer:
  obstacle_range: 3.5
  raytrace_range: 4
  observation_sources: laser
  laser: 
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true


obstacle_camera_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: pcl_main
  front_rgbd_to_scan:
    data_type: LaserScan
    topic: point_cloud_scan_filtered
    marking: true
    clearing: true
