footprint: [[0.5, -0.4], [0.5, 0.4], [-0.5,0.4], [-0.5, -0.4]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.45

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser rear_laser
  front_laser: 
    data_type: LaserScan
    topic: front_laser
    marking: true
    clearing: true

  rear_laser: 
    data_type: LaserScan
    topic: rear_laser
    marking: true
    clearing: true