footprint: [[0.5, -0.4], [0.5, 0.4], [-0.5,0.4], [-0.5, -0.4]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.5

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: laser
  laser: 
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
